AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the Zugzwang::Cloud::IPv6SubnetConfiguration resource type

Globals:
  Function:
    Timeout: 60  # docker start-up times can be long for SAM CLI

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.zugzwang.cloud.ipv6subnetconfiguration.HandlerWrapper::handleRequest
      Runtime: java8
      CodeUri: ./target/zugzwang-cloud-ipv6subnetconfiguration-handler-1.0-SNAPSHOT.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.zugzwang.cloud.ipv6subnetconfiguration.HandlerWrapper::testEntrypoint
      Runtime: java8
      CodeUri: ./target/zugzwang-cloud-ipv6subnetconfiguration-handler-1.0-SNAPSHOT.jar

